### ISSUE TITLE
"Welcome" phrase or similar is missing when logged in

### ISSUE THREAD

**Issue by Magothen** [kappsegla/Remoteyourcar-1#1]
To be able to verify that you are logged in and passed to your own page with your own vehicle it should be good to have some "welcome"-phrase. Right now it's not possible to write auto tests and verify that you have logged in your own account.

**Comment by kappsegla** [comment]
All pages now have a title and pages controlling only one car has a hidden field with the car id.
4ab47860ffc7c0be10c803011789c7099965ece2
