### ISSUE TITLE
Create a new page "Garage" after login 

### ISSUE THREAD

**Issue by Magothen** [kappsegla/Remoteyourcar-1#3]
It should be good to have a new page after login-step. It can be called "garage" and you can use it to:
1. verify that you are loged in
2. to see all your cars with attrubutes (carID, colour, name ..)
From this page you should be able to choose a car and click on it to go to the next step (lock/unlock, set temp, see GPS position ..)

**Comment by kappsegla** [comment]
Fixed by 4ab47860ffc7c0be10c803011789c7099965ece2
