### ISSUE TITLE
log in med fel lösenordet  och fel användarnamn

### ISSUE THREAD

**Issue by wasimeljomaa** [kappsegla/Remoteyourcar-1#4]
jag skriver den här issues för att utveckla frontend.
Där man försöker logga in i hemsidan med fel användarnamn eller fel lösenord, så det skulle komma ett meddelande där det står att antigen användarnamnet eller lösenordet är fel.

**Comment by kappsegla** [comment]
Trying to log in with wrong credentials will now show a text Invalid credentials on the login screen.
4ab47860ffc7c0be10c803011789c7099965ece2
